import type { Metadata } from "next";
import Link from "next/link";
import {
  ArrowRight,
  BarChart3,
  Bot,
  Check,
  FileText,
  Flame,
  Link2,
  MessageSquare,
  PiggyBank,
  TrendingUp,
  Wallet,
  Zap,
} from "lucide-react";

export const metadata: Metadata = {
  title: "FinClear — Your Finances. Automated. Explained.",
  description:
    "AI-powered financial management for small businesses. Connect bank accounts, get automated reports, collaborate with your accountant, and track every dollar.",
  openGraph: {
    title: "FinClear — Your Finances. Automated. Explained.",
    description:
      "AI-powered financial management for small businesses. Connect bank accounts, get automated reports, and track every dollar.",
    type: "website",
    url: "https://finclear.app",
  },
  twitter: {
    card: "summary_large_image",
    title: "FinClear — Your Finances. Automated. Explained.",
    description:
      "AI-powered financial management for small businesses.",
  },
};

const features = [
  {
    name: "Bank Sync",
    description: "Connect accounts via Plaid. Transactions auto-import daily.",
    icon: Wallet,
  },
  {
    name: "AI Reports",
    description: "Monthly P&L, tax deductions, cash flow forecasts generated by AI.",
    icon: Bot,
  },
  {
    name: "Accountant Collaboration",
    description: "Shared inbox, transaction notes, and approval workflows.",
    icon: MessageSquare,
  },
  {
    name: "Document Management",
    description: "Upload receipts, invoices, and contracts. Google Drive sync.",
    icon: FileText,
  },
  {
    name: "Budget Tracking",
    description: "Set budgets by category and track spending vs. targets.",
    icon: PiggyBank,
  },
  {
    name: "Jamaica House Module",
    description: "Market day sales, COGS tracking, and ad ROI for food brands.",
    icon: Flame,
  },
];

const plans = [
  {
    name: "Starter",
    price: 19,
    features: ["1 bank account", "1 user", "100 documents", "Monthly AI reports"],
  },
  {
    name: "Professional",
    price: 49,
    popular: true,
    features: [
      "3 bank accounts",
      "Client + accountant",
      "Unlimited documents",
      "Weekly AI reports",
      "Google Drive sync",
    ],
  },
  {
    name: "Business",
    price: 99,
    features: [
      "Unlimited accounts",
      "Team access",
      "Daily AI reports",
      "Jamaica House module",
      "Priority support",
    ],
  },
];

const faqs = [
  {
    q: "What tax deductions can FinClear find?",
    a: "Our AI analyzes every transaction for business expenses, vehicle costs, home office deductions, professional services, and more. Each deduction is flagged with a confidence level (HIGH/MEDIUM/LOW) so you know exactly what to claim.",
  },
  {
    q: "How secure is my financial data?",
    a: "Bank connections use Plaid (bank-level 256-bit encryption). Access tokens are AES-256-GCM encrypted at rest. We never store your bank passwords. SOC 2 compliant infrastructure on Vercel + Supabase.",
  },
  {
    q: "Can my accountant access my data?",
    a: "Yes. Invite your accountant and they get a dedicated dashboard to view your transactions, add notes, flag items for review, and communicate via the shared inbox.",
  },
  {
    q: "What banks are supported?",
    a: "Via Plaid, FinClear supports 12,000+ financial institutions in the US and Canada including Chase, Bank of America, Wells Fargo, Capital One, and all major banks.",
  },
  {
    q: "Can I cancel anytime?",
    a: "Yes. Cancel anytime from the billing portal. No contracts, no cancellation fees. Your data remains accessible on the free tier.",
  },
  {
    q: "What is the Jamaica House module?",
    a: "A specialized dashboard for food product businesses selling at farmers markets. Track market day sales by location, product performance, cost of goods, vendor fees, and social media ad ROI.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-[#0f0f0f] text-white">
      {/* Google Analytics Placeholder */}
      {/* <Script src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX" /> */}

      {/* Navbar */}
      <nav className="sticky top-0 z-50 border-b border-white/10 bg-[#0f0f0f]/90 backdrop-blur-md">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-lg bg-gradient-to-br from-amber-500 to-amber-700 flex items-center justify-center">
              <span className="text-white font-bold text-sm">FC</span>
            </div>
            <span className="text-lg font-bold">FinClear</span>
          </div>
          <div className="hidden md:flex items-center gap-6 text-sm text-gray-400">
            <a href="#features" className="hover:text-white transition-colors">Features</a>
            <a href="#pricing" className="hover:text-white transition-colors">Pricing</a>
            <a href="#faq" className="hover:text-white transition-colors">FAQ</a>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/sign-in" className="text-sm text-gray-400 hover:text-white transition-colors">
              Sign In
            </Link>
            <Link
              href="/sign-up"
              className="rounded-lg bg-gradient-to-r from-amber-500 to-amber-600 px-4 py-2 text-sm font-medium text-white hover:from-amber-600 hover:to-amber-700 transition-all"
            >
              Get Started Free
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-b from-amber-900/20 to-transparent" />
        <div className="relative mx-auto max-w-6xl px-6 pt-24 pb-20 text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-amber-500/30 bg-amber-500/10 px-3 py-1 text-xs text-amber-400 mb-6">
            <Zap className="h-3 w-3" />
            AI-Powered Financial Intelligence
          </div>
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">
            Your finances.{" "}
            <span className="bg-gradient-to-r from-amber-400 to-amber-600 bg-clip-text text-transparent">
              Automated.
            </span>{" "}
            Explained.
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-gray-400">
            Connect your bank accounts. Let AI analyze every transaction.
            Generate tax-ready reports in seconds. Collaborate with your
            accountant in real time.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/sign-up"
              className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-amber-500 to-amber-600 px-6 py-3 text-base font-semibold text-white hover:from-amber-600 hover:to-amber-700 transition-all shadow-lg shadow-amber-500/25"
            >
              Start Free Trial
              <ArrowRight className="h-4 w-4" />
            </Link>
            <a
              href="#features"
              className="inline-flex items-center gap-2 text-sm text-gray-400 hover:text-white transition-colors"
            >
              See how it works
              <ArrowRight className="h-3 w-3" />
            </a>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="border-t border-white/5 bg-[#0a0a0a]">
        <div className="mx-auto max-w-5xl px-6 py-20">
          <h2 className="text-center text-2xl font-bold mb-12">
            Three steps to financial clarity
          </h2>
          <div className="grid gap-8 md:grid-cols-3">
            {[
              {
                step: "1",
                title: "Connect",
                description: "Link your bank accounts securely via Plaid. Transactions sync automatically.",
                icon: Link2,
              },
              {
                step: "2",
                title: "Analyze",
                description: "AI categorizes spending, identifies deductions, and spots cash flow patterns.",
                icon: TrendingUp,
              },
              {
                step: "3",
                title: "Report",
                description: "Generate P&L statements, tax reports, and forecasts with one click.",
                icon: BarChart3,
              },
            ].map((item) => (
              <div key={item.step} className="text-center">
                <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-amber-500/20 to-amber-700/20 border border-amber-500/20">
                  <item.icon className="h-6 w-6 text-amber-500" />
                </div>
                <div className="text-xs font-medium text-amber-500 mb-2">
                  Step {item.step}
                </div>
                <h3 className="text-lg font-semibold mb-2">{item.title}</h3>
                <p className="text-sm text-gray-400">{item.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="border-t border-white/5">
        <div className="mx-auto max-w-6xl px-6 py-20">
          <h2 className="text-center text-2xl font-bold mb-3">
            Everything you need to manage your money
          </h2>
          <p className="text-center text-gray-400 mb-12">
            Six powerful modules that work together
          </p>
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((feature) => (
              <div
                key={feature.name}
                className="rounded-xl border border-white/10 bg-white/5 p-6 hover:border-amber-500/30 hover:bg-amber-500/5 transition-all"
              >
                <feature.icon className="h-8 w-8 text-amber-500 mb-3" />
                <h3 className="text-base font-semibold mb-1">{feature.name}</h3>
                <p className="text-sm text-gray-400">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="border-t border-white/5 bg-[#0a0a0a]">
        <div className="mx-auto max-w-5xl px-6 py-20">
          <h2 className="text-center text-2xl font-bold mb-3">
            Plans that grow with your business
          </h2>
          <p className="text-center text-gray-400 mb-12">
            Start free, upgrade when ready
          </p>
          <div className="grid gap-6 md:grid-cols-3">
            {plans.map((plan) => (
              <div
                key={plan.name}
                className={`rounded-xl border p-6 ${
                  plan.popular
                    ? "border-amber-500 bg-amber-500/5 relative"
                    : "border-white/10 bg-white/5"
                }`}
              >
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-amber-500 px-3 py-0.5 text-xs font-medium text-white">
                    Most Popular
                  </div>
                )}
                <h3 className="text-lg font-semibold">{plan.name}</h3>
                <div className="mt-3 mb-4">
                  <span className="text-3xl font-bold">${plan.price}</span>
                  <span className="text-sm text-gray-500">/mo</span>
                </div>
                <ul className="space-y-2 mb-6">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-start gap-2 text-sm text-gray-300">
                      <Check className="h-4 w-4 text-amber-500 shrink-0 mt-0.5" />
                      {f}
                    </li>
                  ))}
                </ul>
                <Link
                  href="/sign-up"
                  className={`block w-full rounded-lg py-2.5 text-center text-sm font-medium transition-all ${
                    plan.popular
                      ? "bg-gradient-to-r from-amber-500 to-amber-600 text-white hover:from-amber-600 hover:to-amber-700"
                      : "border border-white/20 text-white hover:bg-white/10"
                  }`}
                >
                  Get Started
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="border-t border-white/5">
        <div className="mx-auto max-w-5xl px-6 py-20">
          <h2 className="text-center text-2xl font-bold mb-12">
            Trusted by small businesses
          </h2>
          <div className="grid gap-6 md:grid-cols-3">
            {[
              { name: "Business Owner", role: "Food Products", quote: "FinClear saves me hours every week. The AI reports are incredible." },
              { name: "Freelancer", role: "Creative Services", quote: "Finally, I can see exactly where my money goes. Tax season is a breeze." },
              { name: "Small Business", role: "Retail", quote: "The accountant collaboration feature changed how we handle bookkeeping." },
            ].map((t, i) => (
              <div
                key={i}
                className="rounded-xl border border-white/10 bg-white/5 p-6"
              >
                <p className="text-sm text-gray-300 mb-4 italic">
                  &ldquo;{t.quote}&rdquo;
                </p>
                <div className="flex items-center gap-3">
                  <div className="h-8 w-8 rounded-full bg-amber-500/20 flex items-center justify-center text-amber-500 text-xs font-bold">
                    {t.name[0]}
                  </div>
                  <div>
                    <p className="text-sm font-medium">{t.name}</p>
                    <p className="text-xs text-gray-500">{t.role}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="border-t border-white/5 bg-[#0a0a0a]">
        <div className="mx-auto max-w-3xl px-6 py-20">
          <h2 className="text-center text-2xl font-bold mb-12">
            Frequently Asked Questions
          </h2>
          <div className="space-y-6">
            {faqs.map((faq, i) => (
              <div key={i} className="border-b border-white/10 pb-6">
                <h3 className="text-base font-semibold mb-2">{faq.q}</h3>
                <p className="text-sm text-gray-400">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-white/5">
        <div className="mx-auto max-w-3xl px-6 py-20 text-center">
          <h2 className="text-3xl font-bold mb-4">
            Ready to take control of your finances?
          </h2>
          <p className="text-gray-400 mb-8">
            Join thousands of small businesses automating their bookkeeping with AI.
          </p>
          <Link
            href="/sign-up"
            className="inline-flex items-center gap-2 rounded-lg bg-gradient-to-r from-amber-500 to-amber-600 px-8 py-3 text-base font-semibold text-white hover:from-amber-600 hover:to-amber-700 transition-all shadow-lg shadow-amber-500/25"
          >
            Start Your Free Trial
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/10 bg-[#080808]">
        <div className="mx-auto max-w-6xl px-6 py-12">
          <div className="grid gap-8 sm:grid-cols-2 md:grid-cols-4">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <div className="h-7 w-7 rounded-lg bg-gradient-to-br from-amber-500 to-amber-700 flex items-center justify-center">
                  <span className="text-white font-bold text-xs">FC</span>
                </div>
                <span className="font-bold">FinClear</span>
              </div>
              <p className="text-xs text-gray-500">
                AI-powered financial management for small businesses.
              </p>
            </div>
            <div>
              <h4 className="text-sm font-medium mb-3">Product</h4>
              <ul className="space-y-2 text-xs text-gray-400">
                <li><a href="#features" className="hover:text-white">Features</a></li>
                <li><a href="#pricing" className="hover:text-white">Pricing</a></li>
                <li><Link href="/sign-up" className="hover:text-white">Sign Up</Link></li>
              </ul>
            </div>
            <div>
              <h4 className="text-sm font-medium mb-3">Support</h4>
              <ul className="space-y-2 text-xs text-gray-400">
                <li><a href="mailto:support@finclear.app" className="hover:text-white">Email Support</a></li>
                <li><a href="#faq" className="hover:text-white">FAQ</a></li>
              </ul>
            </div>
            <div>
              <h4 className="text-sm font-medium mb-3">Legal</h4>
              <ul className="space-y-2 text-xs text-gray-400">
                <li><span className="cursor-default">Privacy Policy</span></li>
                <li><span className="cursor-default">Terms of Service</span></li>
              </ul>
            </div>
          </div>
          <div className="mt-8 border-t border-white/10 pt-8 text-center text-xs text-gray-500">
            &copy; {new Date().getFullYear()} FinClear. All rights reserved.
            <br />
            <span className="text-gray-600">A Signature By Tunde O LLC product.</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
